services:
  backend:
    image: 588738568626.dkr.ecr.eu-north-1.amazonaws.com/sharedgo:latest
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - app-network
  frontend:
    image: 588738568626.dkr.ecr.eu-north-1.amazonaws.com/sharedgo_frontend:latest
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge