name: Deploy to AWS EC2
on:
  push:
    branches: [ "dev", "main"]

env:
  AWS_REGION: eu-north-1
  BACKEND_ECR_REPOSITORY: sharedgo
  FRONTEND_ECR_REPOSITORY: sharedgo_frontend
  IMAGE_TAG: ${{ github.sha }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Backend image to Amazon ECR
        id: build-backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Build the Docker image
          docker build -t $BACKEND_ECR_REPOSITORY:$IMAGE_TAG Backend/
          # Tag the image to ECR
          docker tag $BACKEND_ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/${BACKEND_ECR_REPOSITORY}:latest
          # Push the image to ECR
          docker push $ECR_REGISTRY/${BACKEND_ECR_REPOSITORY}:latest
        
      - name: Build, tag, and push Frontend image to Amazon ECR
        id: build-frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_SOCKET_URL: ${{ secrets.VITE_SOCKET_URL }}

        run: |
          # Build the Docker image
          docker build \
            --build-arg VITE_API_URL=$VITE_API_URL \
            --build-arg VITE_SOCKET_URL=$VITE_SOCKET_URL \
            -t $FRONTEND_ECR_REPOSITORY:$IMAGE_TAG Frontend/
          # Tag the image to ECR
          docker tag $FRONTEND_ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/${FRONTEND_ECR_REPOSITORY}:latest
          # Push the image to ECR
          docker push $ECR_REGISTRY/${FRONTEND_ECR_REPOSITORY}:latest

      
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with: 
          host: sharedgo.link
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: AWS_REGION,ECR_REGISTRY
          script: |
            # login to ECR on the EC2 instance
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
            # navigate to compose file
            cd /home/ec2-user/app
            # Pull the latest images
            docker compose pull
            # Restart the containers 
            docker compose up -d --remove-orphans

        