name: frontend-ci

on:
  push:
    paths: [ "frontend/**" ]
  pull_request:
    paths: [ "frontend/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' #To speed up subsequent runs
        
      - name: Install deps
        run: npm ci

      - name: Type check and linting
        run: |
          npm run lint
          npx tsc --noEmit
        
     # - name: Run tests      #For when tests are implemented in the frontend
     #  run:

      - name: Build project
        run: npm run build
